# Generated by Django 3.2.13 on 2022-05-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.PositiveBigIntegerField()),
                ('unvisible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=255)),
                ('price_without_discount', models.PositiveIntegerField()),
                ('price_with_discount', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('id_articul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articul', to='cards.userarticul')),
            ],
        ),
    ]
