# Generated by Django 3.2.13 on 2022-05-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveBigIntegerField()),
                ('id_user_for_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL, verbose_name='user_article')),
            ],
            options={
                'verbose_name': 'User Article',
                'verbose_name_plural': 'User Articles',
            },
        ),
        migrations.CreateModel(
            name='RecordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=255)),
                ('price_without_discount', models.PositiveIntegerField()),
                ('price_with_discount', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='cards.userarticle')),
                ('id_user_for_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='user_card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
