# Generated by Django 3.2.13 on 2022-05-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserArticul',
            new_name='UserArticle',
        ),
        migrations.AlterModelOptions(
            name='recordcard',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='userarticle',
            options={'verbose_name': 'User Article', 'verbose_name_plural': 'user Articles'},
        ),
        migrations.RenameField(
            model_name='userarticle',
            old_name='articul',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='id_articul',
        ),
        migrations.AddField(
            model_name='recordcard',
            name='id_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='cards.userarticle'),
            preserve_default=False,
        ),
    ]
