# Generated by Django 3.2.13 on 2022-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20220518_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='article',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
