version: "3.3"

services:
  db:
    image: postgres:13-alpine3.14
    env_file:
      - .env_docker

  web:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis
    restart: always

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile_celery
    command: celery -A wildberries_robot worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    env_file:
      - .env_docker
    depends_on:
      - db
      - redis

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile_celery
    command: celery -A notification_service flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - .env_docker
    depends_on:
      - celery  



